// import "../../styles/style.css";
import "./globals.css";
import MouseFollower from "./components/MouseFollower";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <MouseFollower />
        {children}
      </body>
    </html>
  );
}
